### ISSUE TITLE
Interrupt Service Routine

### ISSUE THREAD

**Issue by sajjadahmed677** [lowRISC/ibex#1238]
I need guidance regarding ISR. we have multiple devices in an SoC, and only a single wire indicates the core about external interrupts. so how do we get to know that which device interrupted the core and how we will deal that. for example i wanted to read a value from a GPIO so, what will be the flow of reading the value from GPIO in terms of ISR.

**Comment by GregAC** [comment]
Ibex does have the 'fast' IRQs, these will jump to different points relative to `mtvec` (see the documentation here: https://ibex-core.readthedocs.io/en/latest/03_reference/exception_interrupts.html) allowing you to quickly determine interrupt source.

Otherwise you want some kind of interrupt controller which exposes a memory mapped register you can read which will tell you what cause the interrupt. In RISC-V you have the PLIC specification for such an interrupt controller: https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic.adoc. It's not mandatory to use a PLIC compatible interrupt controller but probably advisable to maintain interoperability with other RISC-V systems.

The OpenTitan repository contains a PLIC implementation: https://github.com/lowRISC/opentitan/tree/master/hw/ip/rv_plic It's designed work with the rest of the OpenTitan SoC but shouldn't be too much work to extract out the 'core' and use it in something else. Especially if you're using tilelink.

**Comment by sajjadahmed677** [comment]
Got it. Thank you @GregAC
