### ISSUE TITLE
Mismatches for `mret` behaviour between Spike and RTL

### ISSUE THREAD

**Issue by ctopal** [lowRISC/ibex#1712]
Whenever we see a `mret` instruction, Spike sets `mstatus.mprv` to 0 and that affects our LSU related PMP checks. Relevant commit that adds this functionality (that comes with newer privilege spec version 20211203) can be found at https://github.com/lowRISC/riscv-isa-sim/commit/327084128246e5cf562293cfe82d2570a6d5629e. Note that in privilege spec v1.11, this `mret` behaviour is not existing and we are officially supporting that version. So, it looks like we have two options

1. Keep spike in line with priv. spec. v1.11 for this one and do the same kind of patching for future mismatches
2. Update Ibex to priv. spec. 20211203

You can see the behaviour in the tests mentioned in https://github.com/lowRISC/ibex/issues/1694

old estimate 32
> estimate 2
> remaining 2022-07-28 1

**Comment by GregAC** [comment]
Certainly the updated version seems more secure, if M mode is doing something using `mprv` and `mret` gets executed without clearing it U mode could end up with M mode access. It adds a new fault injection possibility (e.g. skipping to an mret or somehow inserting one when mprv is getting altered).

**Comment by andreaskurth** [comment]
I tend to agree with updating to more recent privilege spec. I definitely agree that the changes that such a change would bring have to be understood (especially the major ones).

We could compare the sources of the specification (e.g., https://github.com/riscv/riscv-isa-manual/compare/Ratified-IMFDQC-and-Priv-v1.11...draft-20211203-cb99010) and filter for the files that form the privilege spec. That would still require careful examination of differences, but it would probably be less error-prone and more systematic than having the current and the target spec as PDF next to each other and comparing them visually.

Which spec version would we target?

**Comment by vogelpi** [comment]
I would target the last ratified version. Version 1.12 is currently under review, thus it would be the one Canberk referenced. The pdf lists the changes compared to 1.11 Ibex currently supports on Pages i and ii.

**Comment by GregAC** [comment]
So looks like the ratified version is 1.12 it's just pending the integration of some extensions (such an ePMP)?

So really because we have ePMP I think we have to move to 1.12 as 1.11 with ePMP isn't an 'official' architecture config. In particular the mseccfg is defined in 1.12 but not mentioned at all in 1.11

Looks like the changes are very minimal, we'd need to add `menvcfg` but it can just read as zero and ignore writes.

**Comment by GregAC** [comment]
Ah actually it's not so simple there's the `menvcfg` CSR which is new. Some of it relates to cache management extensions which may impact us due to the ICache. Potentially we can do a quick implementation of these (e.g. just treat any of the cache management operations that effect the icache as FENCE.I). More to investigate here.

**Comment by johngt** [comment]
Adding estimate of 32 as there are potentially many areas that will need to be investigated for privilege spec change.

**Comment by GregAC** [comment]
Updated estimate to 2 to cover the work of reverting spike back to the old behaviour. New issue created to cover the move to v1.12 https://github.com/lowRISC/ibex/issues/1733

Remaining work here is packaging a new build of spike cosim so we can get the updated mprv behavior (no clearing) available for CI and regressions.

**Comment by GregAC** [comment]
New version of spike cosim has been released that includes this fix
