### ISSUE TITLE
[dv] Ibex V2S Actions

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1910]
- [x] Follow up on whether existing testing on OT side is sufficient to cover bus integrity errors for TL host. Ibex testbench covers ECC on data but integrity on control signals may be uncovered - @GregAC, https://github.com/lowRISC/opentitan/pull/16107
 - [x] lowRISC/ibex#1911, https://github.com/lowRISC/ibex/pull/1935
 - [x] lowRISC/ibex#1912, https://github.com/lowRISC/ibex/pull/1935
 - [x] Setup Ibex sec_cm FPV flow in OT - https://github.com/lowRISC/opentitan/pull/16156
 - [x] lowRISC/opentitan#16118, https://github.com/lowRISC/opentitan/pull/16156
 - [x] lowRISC/opentitan#16117
 - [x] Cross check coverage plan against testplan - @GregAC, https://github.com/lowRISC/ibex/pull/1943
 - [x] Write up V2S checklist and sec_cm to test mapping in Ibex documentation - https://github.com/lowRISC/ibex/pull/1939

**Comment by GregAC** [comment]
I've made issues for everything that represents new engineering tasks, the rest are just following up/reviewing so didn't bother with separate issues.

**Comment by msfschaffner** [comment]
For the first item above: https://github.com/lowRISC/opentitan/pull/16107 updates the `chip_sw_data_integrity` test so that it also injects faults into instructions of a test program residing in the SRAM, on top of data words in SRAM. This does not explicitly cover command integrity errors on the TL-UL bus, but it may be enough to cover the alert-specific glue logic in the `rv_core_ibex` wrapper, since AFAIK the behavior of the TL-UL host adapter (including data+cmd integrity) is checked in other tests such as the `rv_dm` block level `tl_intg_err` tests.

If we agree that is sufficient, we can link `chip_sw_data_integrity` to the first item and mark it as done once the PR is merged.

CC @weicaiyang @matutem @sriyerg
