### ISSUE TITLE
Problem while installing prerequisites in Examples

### ISSUE THREAD

**Issue by thishakyabb** [lowRISC/ibex#2083]
During the prerequisites installation (To install the python dependancies) after i used the command     pip3 install -U -r python-requirements.txt    I got this Error.
![image0](https://github.com/lowRISC/ibex/assets/106297998/c805097c-10f1-4862-9c17-fa96711e5db7)

I ignored that error and continued to build the simulation using the command fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ibex:ibex_simple_system --RV32E=0 --RV32M=ibex_pkg::RV32MFast    But got these errors. 
![image1](https://github.com/lowRISC/ibex/assets/106297998/d5a3d5fe-83d3-4be5-a719-0b323e37d5c1)
![image2](https://github.com/lowRISC/ibex/assets/106297998/713aaf1a-81f6-4f1c-aecf-37b4de9e246b)

@rswarbrick

**Comment by rswarbrick** [comment]
Sorry, I don't think I know what's going on here. The problem seems to be that the Python on your machine is unable to install dependencies in the way you might expect. The only interesting bit is the first screenshot: the later ones just confirm that the install didn't work :-)

A quick web search turns up https://github.com/pypa/pip/issues/10851, which looks like it might be related? But I'm afraid it doesn't look like an issue with Ibex. Please feel free to re-open if you think there's something we can do to help but I don't think we're going to be able to fix Python on your machine!

Good luck getting things working again.
