### ISSUE TITLE
Installation Issue: FuseSoC build doesn't work

### ISSUE THREAD

**Issue by mattecurro** [lowRISC/ibex#2153]
Ubuntu 22.04
Verilator version: 5.022 2024-02-24 rev v5.020-157-g2b4852048
gcc version: 12.3.0
g++ version: 12.3.0
clang version: 14.0.0

After the installation of all the prerequisites, I'm stuck.
Idk how to solve this, why does it seems that I haven't a C++14 compiler?

![Screenshot from 2024-03-25 10-32-09](https://github.com/lowRISC/ibex/assets/101328021/eac314e2-1612-4eb6-be7d-abd34b2eb0ea)
ERROR: Failed to build lowrisc:ibex:ibex_simple_system:0 : '['make', '-j', '3']'

**Comment by junambi** [comment]
Please remove the "-std=c++11" from the CFLAGS in the examples/simple_system/ibex_simple_system.core file.

This will work. I was able to run the test.

**Comment by rswarbrick** [comment]
Oh I see! It looks like recent versions of Verilator have changed `verilatedos.h` so that it requires C++14. The relevant change was part of Verilator version 5.020, released at the start of this year.

I'm going to open a PR to bump this to `-std=c++14`. I don't think this will cause a tooling issue for anyone: looking through GCC releases, I think this has been supported since GCC 6.1, released in 2016.
