### ISSUE TITLE
Why did you use kGE to estimate area and not the usual units of measurement

### ISSUE THREAD

**Issue by thinhpc1110** [lowRISC/ibex#2208]
I don't understand that why and how did you use kGE to estimate the area and not the usual units of measurement. 
can you teach me how the EDA can convert from the micro met to kGE

**Comment by rswarbrick** [comment]
For the "usual units of measurement", I assume you mean some sort of area (micrometers squared, or similar). The problem is that this value scales with the process node, for rather obvious reasons!

Fortunately, it turns out that "the number of gates" is less dependent on the process node that we use, so is a more stable area estimate. There's a (very bare-bones) note about it at [Wikipedia](https://en.wikipedia.org/wiki/Gate_equivalent).

**Comment by thinhpc1110** [comment]
![image](https://github.com/user-attachments/assets/b76e8648-5b29-43cd-b5f5-0c094e3d0201)
I synthesized by cadence genus like above, so i don't know that is true or false.
