### ISSUE TITLE
when will ibex pass some of the compliance tests

### ISSUE THREAD

**Issue by simon5656** [lowRISC/ibex#98]
I see from #96 Boot Address the comment 'Work is underway to update it to to the current spec' etc.

This is good - my question is when do you think the ibex will be able to run the relevant risc-v compliance suites - as they require at least 1.10, 2.1.

We have tried to run ibex in its dv/uvm /tb testbench with the first few compliance tests but have now halted this work due to many issues needing resolving so felt it was best to ask you to get it work - then we can continue.

Pls give an indication when you expect ibex to pass some of the compliance tests.

thanks
Simon

**Comment by imphil** [comment]
We don't have a clear timeline for that at this moment. The trap and interrupt subsystem is the last component which we know of not being compliant with the latest spec, and work on this issue is underway. Expect this to arrive within the next couple of weeks.

Please open an issue if you discover spec compliance problems for things which don't already have a issue here on GitHub.
